---
- name: Enable dispatcher module.
  copy:
    dest: "{{ _aem_dispatcher_apache_server_root }}/conf.modules.d/01-dispatcher.conf"
    content: "LoadModule dispatcher_module modules/mod_dispatcher.so"
    mode: 0644
  notify: restart apache

- name: Install SELinux Python dependencies.
  package:
    name: >-
      {{ 'libsemanage-python' if ansible_distribution_major_version is version('8', '<') else 'libsemanage-python3' }}
    state: present

- name: Install OpenSSL compatibility version for RHEL/CentOS 8.
  package:
    name: compat-openssl10
    state: present
  when: ansible_distribution_major_version is version('8', '>=')

- name: Configure SELinux to allow Apache to create outbound connections.
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"
