---
- name: Derive module filename from tarball name.
  set_fact:
    _aem_dispatcher_module_filename: >-
      {{ aem_dispatcher_tarball_name | regex_replace('(dispatcher)-([\d|\.]*)-(apache[\d|\.]*).*', '\1-\3-\2.so') }}

- name: Unpack Dispatcher module.
  unarchive:
    src: "{{ aem_dispatcher_download_path }}/{{ aem_dispatcher_tarball_name }}"
    remote_src: yes
    dest: "{{ aem_dispatcher_module_path }}"
    mode: 0755
    owner: root
    group: root
    creates: "{{ aem_dispatcher_module_path }}/{{ _aem_dispatcher_module_filename }}"

- name: Create module link.
  file:
    src: "{{ aem_dispatcher_module_path }}/{{ _aem_dispatcher_module_filename }}"
    dest: "{{ aem_dispatcher_module_path }}/mod_dispatcher.so"
    state: link
    force: yes
