---
name: Release

'on':
  release:
    types:
      - published

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a new import on Galaxy.
        uses: robertdebock/galaxy-action@6e5d9a2d8cc2ff266d4430968880406656aef67d
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
